### ISSUE TITLE
Add Columns - "optional" index

### ISSUE THREAD

**Issue by bulloko** [smartsheet-platform/api-docs#101]
https://smartsheet-platform.github.io/api-docs/#add-columns

> index (zero-based, optional)

If you try to hit the endpoint without index you get the following : 

POST - https://api.smartsheet.com/2.0/sheets/{sheetID}/columns
```
[{
	"title": "test1",
	"type": "TEXT_NUMBER"
}]
```

```
{
  "errorCode" : 1012,
  "message" : "Required object attribute(s) are missing from your request: column.index.",
  "refId" : "5z43rtfol5t1",
  "detail" : {
    "columnTitle" : "Row Id"
  }
}
```

Very much indicating it is not optional.

Making the same request, but just adding an index and it works perfectly.

**Comment by bulloko** [comment]
PR for fix -> https://github.com/smartsheet-platform/api-docs/pull/102

**Comment by kfansler** [comment]
This is in the latest doc update coming out today. Thanks!
