### ISSUE TITLE
Wrong model name on python example for Move Folder (ContainerDestination)

### ISSUE THREAD

**Issue by aricke42** [smartsheet-platform/api-docs#111]
`folder = smartsheet_client.Folders.move_folder(
  4509918431602564,                           # folder_id to be moved
  smartsheet.models.Destination({
    'destination_id': 7960873114331012,     # destination folder_id
    'destination_type': 'folder'
  })
)`
smartsheet.models.Destination _should be_ smartsheet.models.ContainerDestination

**Comment by kfansler** [comment]
Fixed. Thanks for calling this to our attention!
